"use client";

import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@/lib/supabase/browser";
import { Button } from "@/lib/ui/button";

type BudgetRow = { id: string; category: string; limit_amount: number };

const categories = [
  "food",
  "shopping",
  "transport",
  "bills",
  "rent",
  "health",
  "subscriptions",
  "travel",
  "other"
];

export function SettingsPanel() {
  const supabase = useMemo(() => createBrowserClient(), []);
  const [phone, setPhone] = useState("");
  const [budgets, setBudgets] = useState<BudgetRow[]>([]);
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    (async () => {
      const { data: auth } = await supabase.auth.getUser();
      if (!auth.user) return;
      const userId = auth.user.id;

      const [profileRes, budgetsRes] = await Promise.all([
        supabase.from("users").select("phone").eq("id", userId).maybeSingle(),
        supabase.from("budgets").select("id,category,limit_amount").eq("user_id", userId)
      ]);

      if (!active) return;
      setPhone(profileRes.data?.phone ?? "");
      setBudgets((budgetsRes.data ?? []) as BudgetRow[]);
    })();
    return () => {
      active = false;
    };
  }, [supabase]);

  return (
    <div className="flex flex-col gap-6">
      <section className="glass rounded-xl p-5">
        <h2 className="text-lg font-semibold">WhatsApp link</h2>
        <p className="mt-1 text-sm text-text-muted">
          This phone number is used to map inbound WhatsApp messages to your account.
        </p>
        <div className="mt-4 flex flex-col gap-3 md:flex-row md:items-end">
          <label className="flex w-full flex-col gap-1">
            <span className="text-sm font-semibold">Phone (E.164)</span>
            <input
              className="glass rounded-xl px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-accent/40"
              placeholder="+9715xxxxxxxx"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
            />
          </label>
          <Button
            onClick={async () => {
              setStatus(null);
              setError(null);
              const res = await fetch("/api/profile/link-phone", {
                method: "POST",
                headers: { "content-type": "application/json" },
                body: JSON.stringify({ phone })
              });
              if (!res.ok) {
                const j = (await res.json().catch(() => null)) as any;
                setError(j?.error ?? "Failed");
                return;
              }
              setStatus("Saved.");
            }}
          >
            Save
          </Button>
        </div>
      </section>

      <section className="glass rounded-xl p-5">
        <h2 className="text-lg font-semibold">Budgets</h2>
        <p className="mt-1 text-sm text-text-muted">
          Budget alerts are generated by the n8n workflow (or the API), based on your
          monthly spend per category.
        </p>
        <div className="mt-4 flex flex-col gap-3">
          {budgets.map((b) => (
            <div
              key={b.id}
              className="flex flex-col gap-3 md:flex-row md:items-center"
            >
              <div className="flex-1 text-sm font-semibold">{b.category}</div>
              <div className="flex items-center gap-2">
                <input
                  className="glass w-40 rounded-xl px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-accent/40"
                  type="number"
                  min={0}
                  step="1"
                  value={b.limit_amount}
                  onChange={(e) => {
                    const next = Number(e.target.value);
                    setBudgets((prev) =>
                      prev.map((x) => (x.id === b.id ? { ...x, limit_amount: next } : x))
                    );
                  }}
                />
                <Button
                  variant="ghost"
                  onClick={async () => {
                    setStatus(null);
                    setError(null);
                    const { data: auth } = await supabase.auth.getUser();
                    if (!auth.user) {
                      setError("Please log in again.");
                      return;
                    }
                    const { error: updateErr } = await supabase
                      .from("budgets")
                      .update({ limit_amount: b.limit_amount })
                      .eq("id", b.id)
                      .eq("user_id", auth.user.id);
                    if (updateErr) {
                      setError(updateErr.message);
                      return;
                    }
                    setStatus("Budget updated.");
                  }}
                >
                  Update
                </Button>
                <Button
                  variant="ghost"
                  onClick={async () => {
                    setStatus(null);
                    setError(null);
                    const { data: auth } = await supabase.auth.getUser();
                    if (!auth.user) {
                      setError("Please log in again.");
                      return;
                    }
                    const { error: delErr } = await supabase
                      .from("budgets")
                      .delete()
                      .eq("id", b.id)
                      .eq("user_id", auth.user.id);
                    if (delErr) {
                      setError(delErr.message);
                      return;
                    }
                    setBudgets((prev) => prev.filter((x) => x.id !== b.id));
                    setStatus("Deleted.");
                  }}
                >
                  Remove
                </Button>
              </div>
            </div>
          ))}

          <div className="mt-3 flex flex-col gap-3 rounded-xl border border-card-border/60 bg-white/0 p-4 md:flex-row md:items-end">
            <AddBudgetRow
              onAdd={async (category, limit_amount) => {
                setStatus(null);
                setError(null);
                const { data: auth } = await supabase.auth.getUser();
                if (!auth.user) {
                  setError("Please log in again.");
                  return;
                }
                const { data, error: addErr } = await supabase
                  .from("budgets")
                  .insert({ user_id: auth.user.id, category, limit_amount })
                  .select("id,category,limit_amount")
                  .single();
                if (addErr) {
                  setError(addErr.message);
                  return;
                }
                setBudgets((prev) => [...prev, data as BudgetRow]);
                setStatus("Budget added.");
              }}
            />
          </div>
        </div>
      </section>

      {error ? <div className="text-sm text-bad">{error}</div> : null}
      {status ? <div className="text-sm text-good">{status}</div> : null}
    </div>
  );
}

function AddBudgetRow({
  onAdd
}: {
  onAdd: (category: string, limit_amount: number) => Promise<void>;
}) {
  const [category, setCategory] = useState(categories[0] ?? "food");
  const [limit, setLimit] = useState<number>(500);

  return (
    <>
      <label className="flex flex-1 flex-col gap-1">
        <span className="text-sm font-semibold">Category</span>
        <select
          className="glass rounded-xl px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-accent/40"
          value={category}
          onChange={(e) => setCategory(e.target.value)}
        >
          {categories.map((c) => (
            <option key={c} value={c}>
              {c}
            </option>
          ))}
        </select>
      </label>
      <label className="flex flex-col gap-1">
        <span className="text-sm font-semibold">Monthly limit (AED)</span>
        <input
          className="glass w-full rounded-xl px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-accent/40 md:w-44"
          type="number"
          min={0}
          step="1"
          value={limit}
          onChange={(e) => setLimit(Number(e.target.value))}
        />
      </label>
      <Button onClick={() => onAdd(category, limit)}>Add</Button>
    </>
  );
}

